# Inspecting both All_beautry.jsonl and meta_All_Beauty.jsonl

In [2]:
import pandas as pd

reviews = pd.read_json(
    "../data/raw/All_Beauty.jsonl",
    lines=True,
    nrows=5,
)

reviews

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5,Such a lovely scent but not overpowering.,This spray is really nice. It smells really go...,[],B00YQ6X8EO,B00YQ6X8EO,AGKHLEW2SOWHNMFQIJGBECAF7INQ,2020-05-05 14:08:48.923,0,True
1,4,Works great but smells a little weird.,"This product does what I need it to do, I just...",[],B081TJ8YS3,B081TJ8YS3,AGKHLEW2SOWHNMFQIJGBECAF7INQ,2020-05-04 18:10:55.070,1,True
2,5,Yes!,"Smells good, feels great!",[],B07PNNCSP9,B097R46CSY,AE74DYR3QUGVPZJ3P7RFWBGIX7XQ,2020-05-16 21:41:06.052,2,True
3,1,Synthetic feeling,Felt synthetic,[],B09JS339BZ,B09JS339BZ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,2022-01-28 18:13:50.220,0,True
4,5,A+,Love it,[],B08BZ63GMJ,B08BZ63GMJ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,2020-12-30 10:02:43.534,0,True

In [3]:
metadata = pd.read_json(
    "../data/raw/meta_All_Beauty.jsonl",
    lines=True,
    nrows=5,
)

metadata

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,All Beauty,"Howard LC0008 Leather Conditioner, 8-Ounce (4-...",4.8,10,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Howard Products,[],{'Package Dimensions': '7.1 x 5.5 x 3 inches; ...,B01CUPMQZE,NaN
1,All Beauty,Yes to Tomatoes Detoxifying Charcoal Cleanser ...,4.5,3,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Yes To,[],"{'Item Form': 'Powder', 'Skin Type': 'Acne Pro...",B076WQZGPM,NaN
2,All Beauty,Eye Patch Black Adult with Tie Band (6 Per Pack),4.4,26,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Levine Health Products,[],{'Manufacturer': 'Levine Health Products'},B000B658RI,NaN
3,All Beauty,"Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4...",3.1,102,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Cherioll,[],"{'Brand': 'Cherioll', 'Item Form': 'Powder', '...",B088FKY3VD,NaN
4,All Beauty,Precision Plunger Bars for Cartridge Grips – 9...,4.3,7,"[Material: 304 Stainless Steel; Brass tip, Len...",[The Precision Plunger Bars are designed to wo...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Precision,[],{'UPC': '644287689178'},B07NGFDN6G,NaN

In [4]:
reviews.columns

metadata.columns

Index(['main_category', 'title', 'average_rating', 'rating_number', 'features',
       'description', 'price', 'images', 'videos', 'store', 'categories',
       'details', 'parent_asin', 'bought_together'],
      dtype='str')

In [5]:
reviews.info()


metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             5 non-null      int64
 1   title              5 non-null      str
 2   text               5 non-null      str
 3   images             5 non-null      object
 4   asin               5 non-null      str
 5   parent_asin        5 non-null      str
 6   user_id            5 non-null      str
 7   timestamp          5 non-null      datetime64[ms]
 8   helpful_vote       5 non-null      int64
 9   verified_purchase  5 non-null      bool
dtypes: bool(1), datetime64[ms](1), int64(2), object(1), str(5)
memory usage: 1.4+ KB
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   main_category    5 non-null      str
 1   title            5 non-null      str
 2   average_rating   5 non-null      float64
 3   rating_number    5 non-null      int64
 4   features         5 non-null      object
 5   description      5 non-null      object
 6   price            0 non-null      float64
 7   images           5 non-null      object
 8   videos           5 non-null      object
 9   store            5 non-null      str
 10  categories       5 non-null      object
 11  details          5 non-null      object
 12  parent_asin      5 non-null      str
 13  bought_together  0 non-null      float64
dtypes: float64(3), int64(1), object(6), str(4)
memory usage: 1.3+ KB

In [7]:
reviews = pd.read_json(
    "../data/raw/All_Beauty.jsonl",
    lines=True, 
)

metadata = pd.read_json(
    "../data/raw/meta_All_Beauty.jsonl",
    lines=True,
)

In [9]:
print("Reviews shape:", reviews.shape)
print("Metadata shape:", metadata.shape)


reviews.isna().sum()
metadata.isna().sum()

reviews["rating"].value_counts().sort_index()
reviews["rating"].value_counts(normalize=True).sort_index()

Reviews shape: (701528, 10)
Metadata shape: (112590, 14)

rating
1    0.145511
2    0.061343
3    0.080263
4    0.113154
5    0.599728
Name: proportion, dtype: float64

In [10]:
print("Unique parent_asin in reviews:", reviews["parent_asin"].nunique())
print("Unique parent_asin in metadata:", metadata["parent_asin"].nunique())

print()

reviews["parent_asin"].isna().sum()
metadata["parent_asin"].isna().sum()

Unique parent_asin in reviews: 112565
Unique parent_asin in metadata: 112590

np.int64(0)

In [13]:
print("Missing values in reviews:")
print(reviews.isna().sum())

print("\nMissing values in metadata:")
print(metadata.isna().sum())

Missing values in reviews:
rating               0
title                0
text                 0
images               0
asin                 0
parent_asin          0
user_id              0
timestamp            0
helpful_vote         0
verified_purchase    0
dtype: int64

Missing values in metadata:
main_category           0
title                   0
average_rating          0
rating_number           0
features                0
description             0
price               94886
images                  0
videos                  0
store               11331
categories              0
details                 0
parent_asin             0
bought_together    112590
dtype: int64

In [15]:
empty_text = reviews["text"].str.strip().eq("").sum()

print("Empty review texts:", empty_text)

Empty review texts: 720

In [16]:
reviews["text_length"] = reviews["text"].str.len()

reviews["text_length"].describe()

count    701528.000000
mean        173.031641
std         246.924645
min           0.000000
25%          44.000000
50%         102.000000
75%         209.000000
max       14989.000000
Name: text_length, dtype: float64

In [17]:
print("Reviews shorter than 10 characters:",
      (reviews["text_length"] < 10).sum())

print("Reviews shorter than 20 characters:",
      (reviews["text_length"] < 20).sum())

Reviews shorter than 10 characters: 27373
Reviews shorter than 20 characters: 74841

In [18]:
reviews.loc[reviews["text_length"] < 20, ["rating", "text"]].head(20)

     rating                 text
3         1       Felt synthetic
4         5              Love it
38        5      Works very well
52        5          Easy to use
55        5        Great product
57        1    sizing is all off
116       5      Works very well
117       4      Love the colors
160       5  Great for the price
163       5         Good Product
169       5        Great quality
171       3  Cute little earings
319       5            Perfect !
386       5             So comfy
415       5              Love it
417       5          Works great
468       4  Very “rusty” color.
485       4         Good product
486       5                great
491       5       Favorite scent

In [20]:
review_products = set(reviews["parent_asin"])
metadata_products = set(metadata["parent_asin"])

matching_products = review_products & metadata_products

print("Unique products in reviews:", len(review_products))
print("Unique products in metadata:", len(metadata_products))
print("Matching products:", len(matching_products))


print("Review products with metadata:", len(matching_products) / len(review_products))

Unique products in reviews: 112565
Unique products in metadata: 112590
Matching products: 112565
Review products with metadata: 1.0

In [24]:
print("Duplicate review texts:", reviews["text"].duplicated().sum())

duplicate_reviews = reviews.duplicated(subset=["user_id", "parent_asin", "rating", "text"]).sum()

print("Potential duplicate reviews:", duplicate_reviews)

Duplicate review texts: 57899
Potential duplicate reviews: 7299

In [25]:
reviews.loc[
    reviews.duplicated(
        subset=["user_id", "parent_asin", "rating", "text"],
        keep=False),
        ["user_id", "parent_asin", "rating", "text"]
        ].head(20)

,user_id,parent_asin,rating,text
6565,AHT2QS6TYOXWKTNWDD63CMGOUZDQ,B00NT0AR7E,5,Great for the price.
6566,AHT2QS6TYOXWKTNWDD63CMGOUZDQ,B00NT0AR7E,5,Great for the price.
6713,AHLDHIVNLWLVRDISEB76TEMLOG2Q,B00WDKPW9O,5,Very pleasant smell and keeps ur skin Moist.
6714,AHLDHIVNLWLVRDISEB76TEMLOG2Q,B07VQZPHHF,5,Very Useful For Taking A Shower After My Opera...
6715,AHLDHIVNLWLVRDISEB76TEMLOG2Q,B00WDKPW9O,5,Very pleasant smell and keeps ur skin Moist.
6716,AHLDHIVNLWLVRDISEB76TEMLOG2Q,B07VQZPHHF,5,Very Useful For Taking A Shower After My Opera...
7090,AEKMLJQPUBHCKDDHKVC74DYKON6Q,B09NBJJCM6,5,Overall an amazing experience! The seller was ...
7091,AEKMLJQPUBHCKDDHKVC74DYKON6Q,B09NBJJCM6,5,Overall an amazing experience! The seller was ...
8008,AFERA3XEMMGZFV4HXB6LTVTZKNDQ,B01DH7KNZ4,5,Since I am getting back into a more of an orga...
8009,AFERA3XEMMGZFV4HXB6LTVTZKNDQ,B01AYTGWA8,5,Anyone knows-use acetone to remove the toughes...
8010,AFERA3XEMMGZFV4HXB6LTVTZKNDQ,B01DH7KNZ4,5,Since I am getting back into a more of an orga...
8011,AFERA3XEMMGZFV4HXB6LTVTZKNDQ,B01AYTGWA8,5,Anyone knows-use acetone to remove the toughes...
8292,AEKDWV2NZYGECRICKDZ2ANLSKUAA,B0B8Q3WTGP,4,This is a good sized round brush. The core rea...
8295,AEKDWV2NZYGECRICKDZ2ANLSKUAA,B0B8Q3WTGP,4,This is a good sized round brush. The core rea...
8553,AG2XZ2N3OGKGELCALULKCA43EY4Q,B083XH4FYP,5,Easy to install. Lightweight. Got tons of comp...
8557,AG2XZ2N3OGKGELCALULKCA43EY4Q,B083XH4FYP,5,Easy to install. Lightweight. Got tons of comp...
8600,AEZFK2L26IEVD2ZSOIXR5VT3AUBQ,B01N4885PD,5,Really like this. Can't find this large barre...
8602,AEZFK2L26IEVD2ZSOIXR5VT3AUBQ,B01N4885PD,5,Really like this. Can't find this large barre...
8831,AGFPRTZBOS3IBQV2UUDPFBZYERPQ,B00NFX6FJO,2,"I thought these would give loose, lasting curl..."
8832,AGFPRTZBOS3IBQV2UUDPFBZYERPQ,B00NFX6FJO,2,"I thought these would give loose, lasting curl..."

In [26]:
duplicate_reviews_asin = reviews.duplicated(subset=["user_id", "asin", "rating", "text"]).sum()

print("Potential duplicate reviews using asin:", duplicate_reviews_asin)

Potential duplicate reviews using asin: 7276

In [27]:
exact_review_duplicates = reviews.duplicated(
    subset=[
        "user_id",
        "asin",
        "rating",
        "title",
        "text",
        "timestamp"
    ]
).sum()

print("More exact duplicate reviews:", exact_review_duplicates)

More exact duplicate reviews: 7276

In [30]:
reviews.loc[
    reviews.duplicated(
        subset=[
            "user_id",
            "asin",
            "rating",
            "title",
            "text",
            "timestamp"
        ],
        keep=False
    ),
    [
        "user_id",
        "asin",
        "parent_asin",
        "rating",
        "title",
        "text",
        "timestamp"
    ]
].head(20)

,user_id,asin,parent_asin,rating,title,text,timestamp
6565,AHT2QS6TYOXWKTNWDD63CMGOUZDQ,B00NT0AR7E,B00NT0AR7E,5,Five Stars,Great for the price.,2015-09-25 22:07:06.000
6566,AHT2QS6TYOXWKTNWDD63CMGOUZDQ,B00NT0AR7E,B00NT0AR7E,5,Five Stars,Great for the price.,2015-09-25 22:07:06.000
6713,AHLDHIVNLWLVRDISEB76TEMLOG2Q,B00WDKPW9O,B00WDKPW9O,5,Moisturizing ur skin,Very pleasant smell and keeps ur skin Moist.,2022-05-06 20:47:13.211
6714,AHLDHIVNLWLVRDISEB76TEMLOG2Q,B07VQZPHHF,B07VQZPHHF,5,Useful For Showering.,Very Useful For Taking A Shower After My Opera...,2020-01-06 22:05:23.132
6715,AHLDHIVNLWLVRDISEB76TEMLOG2Q,B00WDKPW9O,B00WDKPW9O,5,Moisturizing ur skin,Very pleasant smell and keeps ur skin Moist.,2022-05-06 20:47:13.211
6716,AHLDHIVNLWLVRDISEB76TEMLOG2Q,B07VQZPHHF,B07VQZPHHF,5,Useful For Showering.,Very Useful For Taking A Shower After My Opera...,2020-01-06 22:05:23.132
7090,AEKMLJQPUBHCKDDHKVC74DYKON6Q,B09NBJJCM6,B09NBJJCM6,5,JUST WOW!!!,Overall an amazing experience! The seller was ...,2022-09-15 19:25:47.123
7091,AEKMLJQPUBHCKDDHKVC74DYKON6Q,B09NBJJCM6,B09NBJJCM6,5,JUST WOW!!!,Overall an amazing experience! The seller was ...,2022-09-15 19:25:47.123
8008,AFERA3XEMMGZFV4HXB6LTVTZKNDQ,B01DH7KNZ4,B01DH7KNZ4,5,I was able to get these at a discounted sale p...,Since I am getting back into a more of an orga...,2016-04-13 17:31:16.000
8009,AFERA3XEMMGZFV4HXB6LTVTZKNDQ,B01AYTGWA8,B01AYTGWA8,5,Great stuff-takes of gel polish easily!,Anyone knows-use acetone to remove the toughes...,2016-03-18 18:36:10.000
8010,AFERA3XEMMGZFV4HXB6LTVTZKNDQ,B01DH7KNZ4,B01DH7KNZ4,5,I was able to get these at a discounted sale p...,Since I am getting back into a more of an orga...,2016-04-13 17:31:16.000
8011,AFERA3XEMMGZFV4HXB6LTVTZKNDQ,B01AYTGWA8,B01AYTGWA8,5,Great stuff-takes of gel polish easily!,Anyone knows-use acetone to remove the toughes...,2016-03-18 18:36:10.000
8292,AEKDWV2NZYGECRICKDZ2ANLSKUAA,B0B8Q3WTGP,B0B8Q3WTGP,4,Good round brush,This is a good sized round brush. The core rea...,2022-08-27 15:26:43.219
8295,AEKDWV2NZYGECRICKDZ2ANLSKUAA,B0B8Q3WTGP,B0B8Q3WTGP,4,Good round brush,This is a good sized round brush. The core rea...,2022-08-27 15:26:43.219
8553,AG2XZ2N3OGKGELCALULKCA43EY4Q,B083XH4FYP,B083XH4FYP,5,More than enough hair and extremely affordable,Easy to install. Lightweight. Got tons of comp...,2021-04-12 19:27:33.828
8557,AG2XZ2N3OGKGELCALULKCA43EY4Q,B083XH4FYP,B083XH4FYP,5,More than enough hair and extremely affordable,Easy to install. Lightweight. Got tons of comp...,2021-04-12 19:27:33.828
8600,AEZFK2L26IEVD2ZSOIXR5VT3AUBQ,B00011QUDE,B01N4885PD,5,Really like this. Can't find this large barrel...,Really like this. Can't find this large barre...,2015-06-07 17:17:47.000
8602,AEZFK2L26IEVD2ZSOIXR5VT3AUBQ,B00011QUDE,B01N4885PD,5,Really like this. Can't find this large barrel...,Really like this. Can't find this large barre...,2015-06-07 17:17:47.000
8940,AEHLDL6BZYYWHQPGRICACTTDGZ5Q,B00FQD0LNW,B00FQD0LNW,5,Nice lashes!,Very Nice and thin like I want them often rece...,2016-11-18 13:12:26.000
8947,AEHLDL6BZYYWHQPGRICACTTDGZ5Q,B00FQD0LNW,B00FQD0LNW,5,Nice lashes!,Very Nice and thin like I want them often rece...,2016-11-18 13:12:26.000

In [29]:
duplicate_groups = (
    reviews.groupby(["user_id", "asin", "rating", "title", "text", "timestamp"]).size().sort_values(ascending=False)
)

duplicate_groups.head(20)

user_id                       asin        rating  title                                                                       text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           timestamp
AHK3S32VWSXOBIYYF2MKGXUDRDBA  B008FR532U  5       Produces natural glow on face.                                              Evens out complexion.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2022-01-30 17:27:11.330    10
AHJEGTHANR23UG3PMPA6MMCPV3RA  B0873Y1WFZ  5       Just What I Needed                                                          I wanted to get my daughter's hair braided for our trip. My stylist told me to get Kanekalon pre-stretched hair but I could not find the hair in any of the Sally's stores by my house. I decided to get the hair on Amazon and was not disappointed. When I got to my stylist house, she was braiding another client's hair and she compared the hair. My hair was softer and I got more hair for less than the other client. So far it still looks good even after a day at the beach. This hair does look and feel better than what I've purchased before. Definitely will buy this hair again vs going to the hair supply store.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           2021-10-03 17:07:52.333     8
AHC4WQGKGVP5UQ2FRGWY6TWAOETA  B074W1M23V  5       Highly Moisturizing                                                         Lightweight, smells great, and oh does it softens the hair. Helps the most coarse hair to feel soft days following use.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2021-08-07 13:05:45.944     8
AHUWZSKOOZ475MPMYUKUDQJQTYVQ  B07CHB69Y3  5       Those are so good                                                           These bundles are so good I love them                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2018-12-21 03:19:38.685     8
AEFYI6LZU6TKJZ32LBOFO4CI2ZNA  B0798S8C41  1       Too expensive for such poor quality. There was no improvement and I am ...  Too expensive for such poor quality. There was no improvement and I am starting to think my scalp is worse off than it was before I started using this product. I do agree with other reviews that it feels watered down too much. Had to use more shampoo than all other shampoo's I have tried to get a good lather.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2018-05-07 00:36:17.354     7
AG2MWE5FOYGZUXGKFDD2LBRWY4PQ  B00Q1BNG6C  1       One Star                                                                    This item did nor work from the first day I received it                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2015-01-22 11:43:51.000     7
AEHUG4KT7XXVNRIUYLKMVM576CXQ  B078919VBD  3       Not what we wanted                                                          Performed poorly                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               2023-08-21 01:42:39.574     7
AEZS34HKB5WZQHHJQ2NZQZ5PFZJA  B087PY8ZCQ  5       This product is AMAZING                                                     I have always had a problem of curly, frizzy, messy hair. And while I absolutely love my curls, there are days when I want to have that magazine perfect sleek, silky, STRAIGHT hair! But don't really have the patience to straighten them on my own with a flat iron & don't always have the time to go to a Salon. So I decided to give the simply straight Hair Brush Straightener a try on my thick curly natural hair!!！                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 2020-07-23 04:44:46.366     7
AGICMDY5MI55SBAEKWZNKMQX3TDQ  B014E2CSIQ  2       Jouviance Foundation                                                        Product was a bit dried out so thicker than usual. Same problem as other reviewer, it doesn’t pump well due to thickness.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2018-12-29 16:05:40.658     7

In [33]:
def assign_sentiment(rating):
    if rating <= 2:
        return "negative"
    elif rating == 3:
        return "neutral"
    else:
        return "positive"

reviews["sentiment"] = reviews["rating"].apply(assign_sentiment)

reviews["sentiment"].value_counts()

sentiment
positive    500107
negative    145114
neutral      56307
Name: count, dtype: int64

In [34]:
reviews["sentiment"].value_counts(normalize=True)

sentiment
positive    0.712882
negative    0.206854
neutral     0.080263
Name: proportion, dtype: float64

In [55]:
cleaned_reviews = reviews.copy()

# Remove reviews with empty or whitespace-only text
cleaned_reviews = cleaned_reviews[
    cleaned_reviews["text"].str.strip().ne("")
].copy()

# Remove exact duplicate reviews
cleaned_reviews = cleaned_reviews.drop_duplicates(
    subset=["user_id", "asin", "rating", "title", "text", "timestamp"]
).copy()

# Columns used to identify exact duplicate reviews
duplicate_columns = [
    "user_id",
    "asin",
    "rating",
    "title",
    "text",
    "timestamp"
]

# Remove exact duplicate reviews
cleaned_reviews = cleaned_reviews.drop_duplicates(
    subset=duplicate_columns
).copy()

# Verify that exact duplicates have been removed
print("Exact duplicates after cleaning:", cleaned_reviews.duplicated(
    subset=duplicate_columns
).sum())

# Keep only columns needed later in the project
cleaned_reviews = cleaned_reviews[
    [
        "rating",
        "title",
        "text",
        "asin",
        "parent_asin",
        "sentiment",
    ]
].copy()

cleaned_reviews = cleaned_reviews.reset_index(drop=True)

Exact duplicates after cleaning: 0